[package]
name = "codex-login"
version = { workspace = true }
edition = "2024"

[lints]
workspace = true

[dependencies]
serde_json = "1"
tokio = { version = "1", features = [
    "io-std",
    "macros",
    "process",
    "rt-multi-thread",
    "signal",
] }
